# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_mvrnorm <- function(mu, sigma) {
    .Call('_BSTFA_cpp_mvrnorm', PACKAGE = 'BSTFA', mu, sigma)
}

sampleFactors <- function(Lambda, Pmatprime, FLambdalong, Fmat, y, mulong, Tfullbetalong, Bfullxilong, Omega, SigmaFinv, sigma2, ntimes) {
    .Call('_BSTFA_sampleFactors', PACKAGE = 'BSTFA', Lambda, Pmatprime, FLambdalong, Fmat, y, mulong, Tfullbetalong, Bfullxilong, Omega, SigmaFinv, sigma2, ntimes)
}

sampleFactorsNoConf <- function(Lambda, tempvals, Fmat, Fvar, Omega, SigmaFinv, sigma2, ntimes, nlocs) {
    .Call('_BSTFA_sampleFactorsNoConf', PACKAGE = 'BSTFA', Lambda, tempvals, Fmat, Fvar, Omega, SigmaFinv, sigma2, ntimes, nlocs)
}

submatTest <- function(X, ind) {
    .Call('_BSTFA_submatTest', PACKAGE = 'BSTFA', X, ind)
}

